---
# tasks file for ansible-role-cloud-to-edge-vm
# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# This role provides the ability to manage Azure Iot resources.

- import_tasks: launch-prep.yml
- import_tasks: vm-loop.yml
